# -*- coding: utf-8 -*-
"""Linear Regression (Section2)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EyKaxTwZhJwVOuveh7CvAU9fDwxoH8kf
"""

import pandas
from pandas import DataFrame
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

data = pandas.read_csv("cost_revenue_clean.csv")



data.describe()

X = DataFrame(data, columns=["production_budget_usd"])
Y = DataFrame(data, columns=["worldwide_gross_usd"])

plt.figure(figsize=(14, 8))
plt.scatter(X, Y, alpha=0.2)
plt.title("Film Cost VS Revenue")
plt.xlabel("Production Budget in $")
plt.ylabel("Revenue in $")
plt.ylim(0, 3000000000)
plt.xlim(0, 450000000)
plt.show()

regression = LinearRegression()
regression.fit(X, Y)

"""Slope Coefficient:"""

print(regression.coef_) # Slope Coefficient

print(regression.intercept_) # Intercept



plt.figure(figsize=(14, 8))
plt.scatter(X, Y, alpha=0.2)
plt.title("Film Cost VS Revenue")
plt.xlabel("Production Budget in $")
plt.ylabel("Revenue in $")
plt.ylim(0, 3000000000)
plt.xlim(0, 450000000)
plt.plot(X, regression.predict(X), color="red", linewidth=3)
plt.show()

"""54% for the score is a good quality prediction"""

print(f"Score : {regression.score(X, Y)}")